/** \mainpage Driver Overview
  *
  * \section section_drv_info Driver Information
  * This Sensor Controller Interface driver has been generated by the Texas Instruments Sensor Controller
  * Studio tool:
  * - <b>Project name</b>:     Two Sensor reading
  * - <b>Project file</b>:     C:/Users/krisf/OneDrive/Desktop/UROP SU25/microphone_code/two_sensor_data_collection.scp
  * - <b>Code prefix</b>:      -
  * - <b>Operating system</b>: TI-RTOS
  * - <b>Tool version</b>:     2.9.0.208
  * - <b>Tool patches</b>:     None
  * - <b>Target chip</b>:      CC1310, package QFN48 7x7 RGZ, revision -
  * - <b>Created</b>:          2025-08-29 01:03:43.367
  * - <b>Computer</b>:         SLP-4V3VSV3
  * - <b>User</b>:             krisf
  *
  * No user-provided resource definitions were used to generate this driver.
  *
  * No user-provided procedure definitions were used to generate this driver.
  *
  * Do not edit the generated source code files other than temporarily for debug purposes. Any
  * modifications will be overwritten by the Sensor Controller Studio when generating new output.
  *
  * \section section_drv_modules Driver Modules
  * The driver is divided into three modules:
  * - \ref module_scif_generic_interface, providing the API for:
  *     - Initializing and uninitializing the driver
  *     - Task control (for starting, stopping and executing Sensor Controller tasks)
  *     - Task data exchange (for producing input data to and consume output data from Sensor Controller
  *       tasks)
  * - \ref module_scif_driver_setup, containing:
  *     - The AUX RAM image (Sensor Controller code and data)
  *     - I/O mapping information
  *     - Task data structure information
  *     - Driver setup data, to be used in the driver initialization
  *     - Project-specific functionality
  * - \ref module_scif_osal, for flexible OS support:
  *     - Interfaces with the selected operating system
  *
  * It is possible to use output from multiple Sensor Controller Studio projects in one application. Only
  * one driver setup may be active at a time, but it is possible to switch between these setups. When
  * using this option, there is one instance of the \ref module_scif_generic_interface and
  * \ref module_scif_osal modules, and multiple instances of the \ref module_scif_driver_setup module.
  * This requires that:
  * - The outputs must be generated using the same version of Sensor Controller Studio
  * - The outputs must use the same operating system
  * - The outputs must use different source code prefixes (inserted into all globals of the
  *   \ref module_scif_driver_setup)
  *
  *
  * \section section_project_info Project Description
  * Based on the ADC Data Logger for Launchpad.
  *
  *
  * \subsection section_io_mapping I/O Mapping
  * Task I/O functions are mapped to the following pins:
  * - Reading:
  *     - <b>A: Output of both sensors 0</b>: DIO23
  *     - <b>A: Output of both sensors 1</b>: DIO24
  *
  *
  * \section section_task_info Task Description(s)
  * This driver supports the following task(s):
  *
  *
  * \subsection section_task_desc_reading Reading
  * Samples a two sensors at high rate and stores the values in a circular buffer without notifying the
  * System CPU application.
  * 
  * The System CPU application must wake up periodically, compare the new value of output.head against
  * the previous, and then fetch the latest samples from output.pSamples[].
  *
  */




/** \addtogroup module_scif_driver_setup Driver Setup
  *
  * \section section_driver_setup_overview Overview
  *
  * This driver setup instance has been generated for:
  * - <b>Project name</b>:     Two Sensor reading
  * - <b>Code prefix</b>:      -
  *
  * The driver setup module contains the generated output from the Sensor Controller Studio project:
  * - Location of task control and scheduling data structures in AUX RAM
  * - The AUX RAM image, and the size the image
  * - Task data structure information (location, size and buffer count)
  * - I/O pin mapping translation table
  * - Task resource initialization and uninitialization functions
  * - Hooks for run-time logging
  *
  * @{
  */
#ifndef SCIF_H
#define SCIF_H

#include <stdint.h>
#include <stdbool.h>
#include "scif_framework.h"
#include "scif_osal_tirtos.h"


/// Target chip name
#define SCIF_TARGET_CHIP_NAME_CC1310
/// Target chip package
#define SCIF_TARGET_CHIP_PACKAGE_QFN48_7X7_RGZ

/// Number of tasks implemented by this driver
#define SCIF_TASK_COUNT 1

/// Reading: Task ID
#define SCIF_READING_TASK_ID 0


/// Reading: Size of buffer for data reading (256 for two outputs is usually as big as it can get)
#define SCIF_READING_BUFFER_SIZE 32
/// Reading I/O mapping: Output of both sensors
#define SCIF_READING_DIO_ASENSOR_OUT { 23, 24 }


// All shared data structures in AUX RAM need to be packed
#pragma pack(push, 2)


/// Reading: Task configuration structure
typedef struct {
    uint16_t pAuxioASensorOut[2]; ///< I/O mapping: Output of both sensors
} SCIF_READING_CFG_T;


/// Reading: Task output data structure
typedef struct {
    uint16_t head;         ///< Head for sample reading (indicates the position of current reading in the buffer)
    uint16_t index;        ///< 
    uint16_t samples0[32]; ///< Samples buffer of sensor 0
    uint16_t samples1[32]; ///< Samples buffer of sensor 1
} SCIF_READING_OUTPUT_T;


/// Sensor Controller task data (configuration, input buffer(s), output buffer(s) and internal state)
typedef struct {
    struct {
        SCIF_READING_CFG_T cfg;
        SCIF_READING_OUTPUT_T output;
    } reading;
} SCIF_TASK_DATA_T;

/// Sensor Controller task generic control (located in AUX RAM)
#define scifTaskData    (*((volatile SCIF_TASK_DATA_T*) 0x400E00EA))


// Initialized internal driver data, to be used in the call to \ref scifInit()
extern const SCIF_DATA_T scifDriverSetup;


// Restore previous struct packing setting
#pragma pack(pop)


// AUX I/O re-initialization functions
void scifReinitTaskIo(uint32_t bvTaskIds);


// RTC-based tick generation control
void scifStartRtcTicks(uint32_t tickStart, uint32_t tickPeriod);
void scifStartRtcTicksNow(uint32_t tickPeriod);
void scifStopRtcTicks(void);


#endif
//@}


// Generated by SLP-4V3VSV3 at 2025-08-29 01:03:43.367
